-- =====================================================================
--  Quiz SES — Données de démonstration (OPTIONNEL)
--  À importer APRÈS schema.sql. Tous les quiz arrivent en BROUILLON :
--  la professeure les ouvre elle-même (avec un code d’accès) le jour J.
--  Fichier généré par tools/generate_demo_sql.php
-- =====================================================================

SET NAMES utf8mb4;

INSERT IGNORE INTO classes (name, created_at) VALUES ('2nde 3', UNIX_TIMESTAMP());
INSERT IGNORE INTO classes (name, created_at) VALUES ('1ère SES 1', UNIX_TIMESTAMP());
INSERT IGNORE INTO classes (name, created_at) VALUES ('Tle SES 2', UNIX_TIMESTAMP());

-- Quiz : La croissance économique
INSERT INTO quizzes (title, description, level, chapter, status, access_code, max_attempts, time_limit, shuffle_questions, shuffle_choices, pool_size, feedback_mode, results_released, show_leaderboard, speed_bonus, require_fullscreen, max_exits, exit_action, created_at, updated_at) VALUES ('La croissance économique', 'Quiz de 20 questions sur la croissance économique', 'Terminale', 'Quels sont les sources et les défis de la croissance économique ?', 'draft', NULL, 1, 0, 1, 1, 0, 'release', 0, 1, 1, 1, 0, 'lock', UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
SET @quiz_id = LAST_INSERT_ID();
INSERT INTO questions (quiz_id, position, type, prompt, data, points, time_limit, partial, explanation, created_at, updated_at) VALUES (@quiz_id, 0, 'single', 'Quelle est la différence fondamentale entre « croissance » et « expansion » ?', '{"choices":[{"id":"a","text":"La croissance est de court terme, l''expansion de long terme","correct":false},{"id":"b","text":"La croissance est une augmentation soutenue de la production sur le long terme (+1 an), l''expansion est une hausse de courte durée","correct":true},{"id":"c","text":"Ce sont deux synonymes désignant exactement le même phénomène","correct":false}]}', 1.00, 40, 0, 'La croissance se mesure sur le long terme (au moins 1 an), alors que l''expansion désigne une phase de hausse à court terme de l''activité.', UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO questions (quiz_id, position, type, prompt, data, points, time_limit, partial, explanation, created_at, updated_at) VALUES (@quiz_id, 1, 'single', 'Comment calcule-t-on la valeur ajoutée (VA) d''une entreprise ?', '{"choices":[{"id":"a","text":"Chiffre d''affaires + Consommation intermédiaire","correct":false},{"id":"b","text":"Chiffre d''affaires – Consommation intermédiaire","correct":true},{"id":"c","text":"PIB / nombre d''habitants","correct":false}]}', 1.00, 40, 0, 'VA = Chiffre d''affaires – Consommation intermédiaire. Le PIB est la somme de toutes les valeurs ajoutées de l''économie.', UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO questions (quiz_id, position, type, prompt, data, points, time_limit, partial, explanation, created_at, updated_at) VALUES (@quiz_id, 2, 'single', 'Pourquoi utilise-t-on le PIB réel (et non le PIB nominal) pour calculer le taux de croissance ?', '{"choices":[{"id":"a","text":"Parce que le PIB réel est plus simple à calculer","correct":false},{"id":"b","text":"Pour supprimer l''effet de l''inflation et mesurer la vraie évolution de la production","correct":true},{"id":"c","text":"Parce que le PIB nominal n''existe pas vraiment","correct":false}]}', 1.00, 40, 0, 'Le PIB nominal inclut la hausse des prix (inflation). Le PIB réel corrige cet effet pour ne mesurer que l''évolution réelle des quantités produites.', UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO questions (quiz_id, position, type, prompt, data, points, time_limit, partial, explanation, created_at, updated_at) VALUES (@quiz_id, 3, 'single', 'Un pays double sa quantité de travail et de capital, et son PIB double exactement dans les mêmes proportions. Quel type de croissance cela illustre-t-il ?', '{"choices":[{"id":"a","text":"Croissance intensive","correct":false},{"id":"b","text":"Croissance extensive","correct":true},{"id":"c","text":"Une récession","correct":false}]}', 1.00, 40, 0, 'C''est la définition de la croissance extensive : le PIB augmente au même rythme que les facteurs de production (rendements d''échelle constants).', UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO questions (quiz_id, position, type, prompt, data, points, time_limit, partial, explanation, created_at, updated_at) VALUES (@quiz_id, 4, 'single', 'Selon la loi des rendements marginaux décroissants, si on augmente un seul facteur de production (en gardant l''autre fixe) :', '{"choices":[{"id":"a","text":"La production augmente indéfiniment, dans les mêmes proportions","correct":false},{"id":"b","text":"La production augmente, mais de moins en moins vite","correct":true},{"id":"c","text":"La production diminue immédiatement","correct":false}]}', 1.00, 40, 0, 'Chaque unité supplémentaire du facteur apporte un supplément de production de plus en plus faible (ex : l''exemple de la pizza dans le cours).', UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO questions (quiz_id, position, type, prompt, data, points, time_limit, partial, explanation, created_at, updated_at) VALUES (@quiz_id, 5, 'single', 'Pourquoi la croissance extensive n''est-elle pas soutenable indéfiniment ?', '{"choices":[{"id":"a","text":"Parce que les rendements marginaux des facteurs sont décroissants : accumuler indéfiniment travail et capital devient de moins en moins efficace","correct":true},{"id":"b","text":"Parce qu''il n''y a jamais assez de main-d''œuvre disponible","correct":false},{"id":"c","text":"Parce que la loi l''interdit au bout d''un moment","correct":false}]}', 1.00, 40, 0, 'À cause des rendements décroissants, la seule accumulation de F(T) et F(K) finit par ne plus suffire à expliquer/soutenir la croissance.', UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO questions (quiz_id, position, type, prompt, data, points, time_limit, partial, explanation, created_at, updated_at) VALUES (@quiz_id, 6, 'single', 'Qu''est-ce que la Productivité Globale des Facteurs (PGF) ?', '{"choices":[{"id":"a","text":"La quantité totale de travail et de capital utilisée dans l''économie","correct":false},{"id":"b","text":"Le résidu de croissance qui n''est pas expliqué par l''augmentation des quantités de facteurs de production","correct":true},{"id":"c","text":"Le taux de chômage global d''un pays","correct":false}]}', 1.00, 40, 0, 'F(T) + F(K) + ? = Croissance. Ce « ? », résidu inexpliqué par les quantités de facteurs, est la PGF (les gains de productivité).', UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO questions (quiz_id, position, type, prompt, data, points, time_limit, partial, explanation, created_at, updated_at) VALUES (@quiz_id, 7, 'single', 'Un pays voit son PIB augmenter fortement alors que ses quantités de travail et de capital sont restées quasiment identiques. Quel type de croissance illustre le mieux cette situation ?', '{"choices":[{"id":"a","text":"Croissance extensive","correct":false},{"id":"b","text":"Croissance intensive (grâce à la PGF)","correct":true},{"id":"c","text":"Aucune croissance n''est possible dans ce cas","correct":false}]}', 1.00, 40, 0, 'Quand la croissance provient surtout de la hausse de la PGF, à quantité de facteurs quasi constante, on parle de croissance intensive.', UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO questions (quiz_id, position, type, prompt, data, points, time_limit, partial, explanation, created_at, updated_at) VALUES (@quiz_id, 8, 'single', 'Parmi les propositions suivantes, laquelle n''est PAS une source de gains de PGF ?', '{"choices":[{"id":"a","text":"L''amélioration de l''organisation des tâches","correct":false},{"id":"b","text":"L''augmentation du nombre d''heures travaillées","correct":true},{"id":"c","text":"Le progrès technique contenu dans les machines","correct":false}]}', 1.00, 40, 0, 'Travailler plus d''heures, c''est augmenter la quantité de facteur travail (F(T)), pas la productivité : ce n''est donc pas un gain de PGF.', UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO questions (quiz_id, position, type, prompt, data, points, time_limit, partial, explanation, created_at, updated_at) VALUES (@quiz_id, 9, 'single', 'Grâce aux gains de PGF, une entreprise réduit ses coûts et augmente les salaires de ses employés. Quel est l''effet indirect probable sur la demande ?', '{"choices":[{"id":"a","text":"La hausse du pouvoir d''achat des employés stimule leur consommation, ce qui incite les entreprises à produire davantage","correct":true},{"id":"b","text":"Les employés vont automatiquement épargner tout leur salaire sans jamais consommer","correct":false},{"id":"c","text":"Cela n''a aucun effet sur le reste de l''économie","correct":false}]}', 1.00, 40, 0, 'Salaires ↗️ → pouvoir d''achat ↗️ → consommation ↗️ → incite les entreprises à produire davantage pour répondre à la demande.', UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO questions (quiz_id, position, type, prompt, data, points, time_limit, partial, explanation, created_at, updated_at) VALUES (@quiz_id, 10, 'single', 'Pourquoi dit-on que le progrès technique (PT) est devenu « endogène » depuis les années 1980 ?', '{"choices":[{"id":"a","text":"Parce qu''il vient de l''extérieur du système économique, comme un choc imprévisible","correct":false},{"id":"b","text":"Parce qu''il trouve son origine à l''intérieur même du système économique, expliqué par l''innovation et la R&D","correct":true},{"id":"c","text":"Parce qu''il n''a aucune cause identifiable","correct":false}]}', 1.00, 40, 0, 'Endogène = expliqué de l''intérieur du modèle économique (par l''innovation, la R&D...), contrairement à « exogène » (avant les années 80).', UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO questions (quiz_id, position, type, prompt, data, points, time_limit, partial, explanation, created_at, updated_at) VALUES (@quiz_id, 11, 'single', 'Pourquoi une entreprise a-t-elle intérêt à innover la première ?', '{"choices":[{"id":"a","text":"Parce que la loi l''oblige à innover régulièrement","correct":false},{"id":"b","text":"Parce qu''elle se retrouve temporairement en situation de monopole et peut ainsi augmenter ses profits","correct":true},{"id":"c","text":"Parce que l''innovation ne coûte jamais rien à mettre en place","correct":false}]}', 1.00, 40, 0, 'En innovant, l''entreprise devient (temporairement) seule offreuse sur le marché : monopole temporaire, marge et CA plus élevés, jusqu''à ce que les autres la copient.', UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO questions (quiz_id, position, type, prompt, data, points, time_limit, partial, explanation, created_at, updated_at) VALUES (@quiz_id, 12, 'single', 'Que désigne le concept de « destruction créatrice » de Schumpeter ?', '{"choices":[{"id":"a","text":"Le fait que l''innovation ne détruit jamais aucune activité existante","correct":false},{"id":"b","text":"Le fait que les nouvelles innovations rendent les anciennes activités moins rentables, voire les font disparaître, tout en créant de nouvelles opportunités","correct":true},{"id":"c","text":"La destruction des ressources naturelles causée par la croissance","correct":false}]}', 1.00, 40, 0, 'Exemple du cours : le streaming a rendu les CD obsolètes. L''innovation détruit certaines activités tout en en créant de nouvelles.', UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO questions (quiz_id, position, type, prompt, data, points, time_limit, partial, explanation, created_at, updated_at) VALUES (@quiz_id, 13, 'single', 'Un brevet incite une entreprise à investir dans l''innovation principalement parce qu''il :', '{"choices":[{"id":"a","text":"Oblige toutes les autres entreprises à investir aussi","correct":false},{"id":"b","text":"Protège contre la copie, garantissant que l''entreprise profitera des résultats de ses efforts","correct":true},{"id":"c","text":"Réduit automatiquement les impôts de l''entreprise","correct":false}]}', 1.00, 40, 0, 'Le droit de propriété (ex : le brevet) protège contre la copie, ce qui incite à investir puisqu''on est sûr de pouvoir en tirer les bénéfices.', UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO questions (quiz_id, position, type, prompt, data, points, time_limit, partial, explanation, created_at, updated_at) VALUES (@quiz_id, 14, 'single', 'Quelle est la différence entre les institutions « de réglementation » et les institutions « de stabilisation » ?', '{"choices":[{"id":"a","text":"Les premières protègent la concurrence et luttent contre les abus de position dominante ; les secondes réduisent l''instabilité économique (ex : lutte contre l''inflation)","correct":true},{"id":"b","text":"Les premières s''occupent uniquement d''éducation, les secondes uniquement de santé","correct":false},{"id":"c","text":"Elles désignent exactement la même chose","correct":false}]}', 1.00, 40, 0, 'Réglementation → concurrence, ententes, positions dominantes. Stabilisation → instabilité économique, inflation, épargne (ex : banque centrale).', UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO questions (quiz_id, position, type, prompt, data, points, time_limit, partial, explanation, created_at, updated_at) VALUES (@quiz_id, 15, 'single', 'Dans un pays aux institutions « extractives », que se passe-t-il généralement ?', '{"choices":[{"id":"a","text":"Le pouvoir économique et politique est largement partagé, ce qui stimule l''investissement","correct":false},{"id":"b","text":"Une élite s''approprie une grande partie des richesses, ce qui décourage l''épargne, l''investissement et l''innovation","correct":true},{"id":"c","text":"Les droits de propriété y sont particulièrement bien protégés pour tous","correct":false}]}', 1.00, 40, 0, 'Institutions extractives = une élite capte les richesses → peu d''incitation à épargner/investir/innover → cela freine la croissance.', UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO questions (quiz_id, position, type, prompt, data, points, time_limit, partial, explanation, created_at, updated_at) VALUES (@quiz_id, 16, 'single', 'Pourquoi les droits de propriété favorisent-ils la croissance économique ?', '{"choices":[{"id":"a","text":"Parce qu''ils empêchent totalement toute concurrence entre entreprises","correct":false},{"id":"b","text":"Parce qu''ils garantissent à une personne ou une entreprise de pouvoir tirer les revenus de ses efforts, ce qui incite à investir et innover","correct":true},{"id":"c","text":"Parce qu''ils sont entièrement gratuits pour l''État","correct":false}]}', 1.00, 40, 0, 'Sachant qu''elles pourront profiter des résultats de leurs efforts, les entreprises sont incitées à investir, innover, et donc à faire croître l''économie.', UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO questions (quiz_id, position, type, prompt, data, points, time_limit, partial, explanation, created_at, updated_at) VALUES (@quiz_id, 17, 'single', 'Le progrès technique peut créer une « polarisation des emplois ». Que signifie ce phénomène ?', '{"choices":[{"id":"a","text":"Tous les emplois deviennent identiques et également qualifiés","correct":false},{"id":"b","text":"Le PT favorise à la fois les emplois très qualifiés et les emplois peu qualifiés non-routiniers, au détriment des emplois routiniers et intermédiaires","correct":true},{"id":"c","text":"Le progrès technique ne détruit jamais aucun emploi","correct":false}]}', 1.00, 40, 0, 'Ex : les robots remplacent des tâches industrielles routinières, mais créent des emplois très qualifiés ; les emplois peu qualifiés non routiniers subsistent.', UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO questions (quiz_id, position, type, prompt, data, points, time_limit, partial, explanation, created_at, updated_at) VALUES (@quiz_id, 18, 'single', 'L''« effet superstar » permis par les technologies numériques explique pourquoi :', '{"choices":[{"id":"a","text":"Tous les travailleurs finissent par gagner le même salaire","correct":false},{"id":"b","text":"Quelques individus très talentueux (sportifs, artistes...) peuvent toucher un marché mondial à très faible coût, captant une part disproportionnée des revenus","correct":true},{"id":"c","text":"Les entreprises n''ont plus du tout besoin d''innover","correct":false}]}', 1.00, 40, 0, 'Les technologies numériques permettent de diffuser une œuvre/un service à très faible coût à un très grand nombre de personnes dans le monde entier.', UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO questions (quiz_id, position, type, prompt, data, points, time_limit, partial, explanation, created_at, updated_at) VALUES (@quiz_id, 19, 'single', 'Concernant les limites écologiques de la croissance, quelle affirmation est correcte ?', '{"choices":[{"id":"a","text":"Les ressources renouvelables ne peuvent jamais être menacées, contrairement aux ressources non renouvelables","correct":false},{"id":"b","text":"Les ressources non renouvelables (pétrole, gaz, minerais) sont en quantité limitée, et même les ressources renouvelables peuvent être surexploitées (ex : la surpêche)","correct":true},{"id":"c","text":"La croissance économique n''a aucun impact sur l''environnement","correct":false}]}', 1.00, 40, 0, 'Non renouvelables = quantité limitée (pétrole, gaz...). Renouvelables (poissons, forêts, eau) peuvent aussi s''épuiser si elles sont surexploitées, comme la surpêche.', UNIX_TIMESTAMP(), UNIX_TIMESTAMP());

-- Quiz : Exemple – Tous les types de questions
INSERT INTO quizzes (title, description, level, chapter, status, access_code, max_attempts, time_limit, shuffle_questions, shuffle_choices, pool_size, feedback_mode, results_released, show_leaderboard, speed_bonus, require_fullscreen, max_exits, exit_action, created_at, updated_at) VALUES ('Exemple – Tous les types de questions', 'Quiz d’exemple (brouillon) montrant les 6 types de questions : choix unique, choix multiples, vrai/faux, réponse courte, numérique, remise en ordre.', 'Terminale', 'Quels sont les sources et les défis de la croissance économique ?', 'draft', NULL, 1, 0, 1, 1, 0, 'immediate', 0, 1, 1, 1, 1, 'lock', UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
SET @quiz_id = LAST_INSERT_ID();
INSERT INTO questions (quiz_id, position, type, prompt, data, points, time_limit, partial, explanation, created_at, updated_at) VALUES (@quiz_id, 0, 'single', 'Le PIB (produit intérieur brut) mesure…', '{"choices":[{"id":"a","text":"la richesse produite sur le territoire national pendant une période donnée","correct":true},{"id":"b","text":"le patrimoine accumulé par les habitants d’un pays","correct":false},{"id":"c","text":"les revenus perçus par les seuls résidents français","correct":false},{"id":"d","text":"la différence entre les exportations et les importations","correct":false}]}', 1.00, 20, 0, 'Le PIB est la somme des valeurs ajoutées produites par les unités résidentes sur le territoire pendant une période donnée (en général un an).', UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO questions (quiz_id, position, type, prompt, data, points, time_limit, partial, explanation, created_at, updated_at) VALUES (@quiz_id, 1, 'numeric', 'Le PIB d’un pays passe de 2 000 à 2 100 milliards d’euros en un an.
Quel est le taux de croissance du PIB (en %) ?', '{"value":5,"tolerance":0.05,"unit":"%"}', 1.00, 45, 0, '(2 100 − 2 000) / 2 000 × 100 = 5 %.', UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO questions (quiz_id, position, type, prompt, data, points, time_limit, partial, explanation, created_at, updated_at) VALUES (@quiz_id, 2, 'multiple', 'Selon les théories de la croissance endogène, quelles sont des sources de croissance auto-entretenue ?', '{"choices":[{"id":"a","text":"L’accumulation de capital humain","correct":true},{"id":"b","text":"La recherche-développement","correct":true},{"id":"c","text":"Les infrastructures publiques","correct":true},{"id":"d","text":"La baisse de la population active","correct":false}]}', 2.00, 30, 1, 'Romer, Lucas et Barro montrent que le capital humain, les connaissances (R&D) et le capital public produisent des externalités positives qui entretiennent la croissance.', UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO questions (quiz_id, position, type, prompt, data, points, time_limit, partial, explanation, created_at, updated_at) VALUES (@quiz_id, 3, 'truefalse', 'La productivité globale des facteurs (PGF) mesure la part de la croissance qui n’est expliquée ni par la hausse du travail ni par celle du capital.', '{"answer":true}', 1.00, 20, 0, 'C’est le « résidu » de Solow, en grande partie attribué au progrès technique.', UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO questions (quiz_id, position, type, prompt, data, points, time_limit, partial, explanation, created_at, updated_at) VALUES (@quiz_id, 4, 'short', 'Quel économiste a popularisé la notion de « destruction créatrice » ?', '{"answers":["Schumpeter","Joseph Schumpeter","Joseph Alois Schumpeter"],"tolerance":true}', 1.00, 30, 0, 'Joseph Schumpeter, Capitalisme, socialisme et démocratie (1942).', UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO questions (quiz_id, position, type, prompt, data, points, time_limit, partial, explanation, created_at, updated_at) VALUES (@quiz_id, 5, 'ordering', 'Classe ces économies de la plus grande à la plus petite selon leur PIB en 2023 (en dollars courants).', '{"items":[{"id":"a","text":"États-Unis"},{"id":"b","text":"Chine"},{"id":"c","text":"Allemagne"},{"id":"d","text":"France"}]}', 1.00, 40, 1, 'Selon le FMI : États-Unis (≈ 27 400 Md$), Chine (≈ 17 800 Md$), Allemagne (≈ 4 500 Md$), France (≈ 3 000 Md$).', UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO questions (quiz_id, position, type, prompt, data, points, time_limit, partial, explanation, created_at, updated_at) VALUES (@quiz_id, 6, 'single', 'Quelle conception de la soutenabilité considère que le capital naturel peut être compensé par du capital physique ou humain ?', '{"choices":[{"id":"a","text":"La soutenabilité faible","correct":true},{"id":"b","text":"La soutenabilité forte","correct":false},{"id":"c","text":"La décroissance","correct":false},{"id":"d","text":"L’empreinte écologique","correct":false}]}', 1.00, 25, 0, 'La soutenabilité faible postule que les capitaux sont substituables ; la soutenabilité forte considère que certains éléments du capital naturel sont irremplaçables.', UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO questions (quiz_id, position, type, prompt, data, points, time_limit, partial, explanation, created_at, updated_at) VALUES (@quiz_id, 7, 'single', 'Quel organisme publie les chiffres officiels de la croissance française ?', '{"choices":[{"id":"a","text":"L’Insee","correct":true},{"id":"b","text":"La Banque centrale européenne","correct":false},{"id":"c","text":"Le FMI","correct":false},{"id":"d","text":"L’OCDE","correct":false}]}', 1.00, 20, 0, 'L’Insee (Institut national de la statistique et des études économiques) publie les comptes nationaux trimestriels.', UNIX_TIMESTAMP(), UNIX_TIMESTAMP());

-- Quiz : Le marché et la formation des prix
INSERT INTO quizzes (title, description, level, chapter, status, access_code, max_attempts, time_limit, shuffle_questions, shuffle_choices, pool_size, feedback_mode, results_released, show_leaderboard, speed_bonus, require_fullscreen, max_exits, exit_action, created_at, updated_at) VALUES ('Le marché et la formation des prix', 'Offre, demande, équilibre et ajustement par les prix.', 'Seconde', 'Comment un marché concurrentiel fonctionne-t-il ?', 'draft', '482913', 1, 0, 1, 1, 0, 'release', 0, 1, 1, 1, 0, 'lock', UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
SET @quiz_id = LAST_INSERT_ID();
INSERT INTO questions (quiz_id, position, type, prompt, data, points, time_limit, partial, explanation, created_at, updated_at) VALUES (@quiz_id, 0, 'single', 'Sur un marché concurrentiel, si la demande augmente (toutes choses égales par ailleurs), le prix d’équilibre…', '{"choices":[{"id":"a","text":"augmente","correct":true},{"id":"b","text":"diminue","correct":false},{"id":"c","text":"ne change pas","correct":false},{"id":"d","text":"devient nul","correct":false}]}', 1.00, 25, 0, 'La courbe de demande se déplace vers la droite : le nouveau point d’équilibre correspond à un prix et une quantité plus élevés.', UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO questions (quiz_id, position, type, prompt, data, points, time_limit, partial, explanation, created_at, updated_at) VALUES (@quiz_id, 1, 'truefalse', 'La courbe d’offre est généralement croissante : plus le prix est élevé, plus les producteurs souhaitent vendre.', '{"answer":true}', 1.00, 20, 0, 'Un prix plus élevé rend la production plus rentable, les offreurs augmentent les quantités proposées.', UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO questions (quiz_id, position, type, prompt, data, points, time_limit, partial, explanation, created_at, updated_at) VALUES (@quiz_id, 2, 'numeric', 'Le prix d’un bien passe de 50 € à 40 €.
Quel est le taux de variation du prix (en %) ?', '{"value":-20,"tolerance":0.05,"unit":"%"}', 1.00, 45, 0, '(40 − 50) / 50 × 100 = −20 %.', UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO questions (quiz_id, position, type, prompt, data, points, time_limit, partial, explanation, created_at, updated_at) VALUES (@quiz_id, 3, 'short', 'Comment appelle-t-on la situation dans laquelle la quantité offerte est égale à la quantité demandée ?', '{"answers":["équilibre","équilibre du marché","équilibre de marché","équilibre de l’offre et de la demande"],"tolerance":true}', 1.00, 30, 0, 'C’est l’équilibre du marché : il détermine le prix et la quantité d’équilibre.', UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO questions (quiz_id, position, type, prompt, data, points, time_limit, partial, explanation, created_at, updated_at) VALUES (@quiz_id, 4, 'multiple', 'Quels éléments provoquent un déplacement de la courbe de demande d’un bien ?', '{"choices":[{"id":"a","text":"Une hausse du revenu des consommateurs","correct":true},{"id":"b","text":"Une variation du prix d’un bien substituable","correct":true},{"id":"c","text":"Un changement dans les goûts des consommateurs","correct":true},{"id":"d","text":"Une variation du prix du bien lui-même","correct":false}]}', 2.00, 35, 1, 'Une variation du prix du bien lui-même provoque un déplacement le long de la courbe, et non un déplacement de la courbe.', UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO questions (quiz_id, position, type, prompt, data, points, time_limit, partial, explanation, created_at, updated_at) VALUES (@quiz_id, 5, 'single', 'Un prix plancher fixé au-dessus du prix d’équilibre provoque…', '{"choices":[{"id":"a","text":"un excédent d’offre","correct":true},{"id":"b","text":"une pénurie","correct":false},{"id":"c","text":"un retour immédiat à l’équilibre","correct":false},{"id":"d","text":"une hausse de la quantité demandée","correct":false}]}', 1.00, 25, 0, 'Au-dessus du prix d’équilibre, la quantité offerte dépasse la quantité demandée : il y a un excédent d’offre (ex. : SMIC et chômage selon l’analyse néoclassique).', UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO questions (quiz_id, position, type, prompt, data, points, time_limit, partial, explanation, created_at, updated_at) VALUES (@quiz_id, 6, 'ordering', 'Remets dans l’ordre le mécanisme d’ajustement d’un marché en situation de pénurie.', '{"items":[{"id":"a","text":"La quantité demandée dépasse la quantité offerte"},{"id":"b","text":"Le prix augmente"},{"id":"c","text":"La quantité demandée baisse et la quantité offerte augmente"},{"id":"d","text":"Le marché revient à l’équilibre"}]}', 1.00, 45, 1, 'La hausse du prix fait converger l’offre et la demande jusqu’au prix d’équilibre.', UNIX_TIMESTAMP(), UNIX_TIMESTAMP());

-- Quiz : La socialisation
INSERT INTO quizzes (title, description, level, chapter, status, access_code, max_attempts, time_limit, shuffle_questions, shuffle_choices, pool_size, feedback_mode, results_released, show_leaderboard, speed_bonus, require_fullscreen, max_exits, exit_action, created_at, updated_at) VALUES ('La socialisation', 'Instances et processus de socialisation, primaire et secondaire.', 'Première', 'Comment la socialisation contribue-t-elle à expliquer les différences de comportement des individus ?', 'draft', NULL, 1, 0, 1, 1, 0, 'end', 0, 0, 1, 1, 0, 'lock', UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
SET @quiz_id = LAST_INSERT_ID();
INSERT INTO questions (quiz_id, position, type, prompt, data, points, time_limit, partial, explanation, created_at, updated_at) VALUES (@quiz_id, 0, 'single', 'La socialisation primaire se déroule principalement…', '{"choices":[{"id":"a","text":"pendant l’enfance","correct":true},{"id":"b","text":"à l’âge adulte","correct":false},{"id":"c","text":"au moment de la retraite","correct":false},{"id":"d","text":"uniquement sur le lieu de travail","correct":false}]}', 1.00, 20, 0, 'La socialisation primaire correspond à l’enfance ; elle est principalement assurée par la famille et l’école.', UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO questions (quiz_id, position, type, prompt, data, points, time_limit, partial, explanation, created_at, updated_at) VALUES (@quiz_id, 1, 'multiple', 'Parmi les éléments suivants, lesquels sont des instances de socialisation ?', '{"choices":[{"id":"a","text":"La famille","correct":true},{"id":"b","text":"L’école","correct":true},{"id":"c","text":"Le groupe de pairs","correct":true},{"id":"d","text":"Les médias","correct":true},{"id":"e","text":"Le code génétique","correct":false}]}', 2.00, 30, 1, 'La socialisation est un processus social : le code génétique n’est pas une instance de socialisation.', UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO questions (quiz_id, position, type, prompt, data, points, time_limit, partial, explanation, created_at, updated_at) VALUES (@quiz_id, 2, 'truefalse', 'Pour Émile Durkheim, l’éducation est une « socialisation méthodique de la jeune génération ».', '{"answer":true}', 1.00, 20, 0, 'Durkheim, Éducation et sociologie (1922).', UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO questions (quiz_id, position, type, prompt, data, points, time_limit, partial, explanation, created_at, updated_at) VALUES (@quiz_id, 3, 'short', 'Quel sociologue a développé la notion d’habitus ?', '{"answers":["Bourdieu","Pierre Bourdieu"],"tolerance":true}', 1.00, 30, 0, 'Pierre Bourdieu : l’habitus désigne un ensemble de dispositions durables acquises par la socialisation.', UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO questions (quiz_id, position, type, prompt, data, points, time_limit, partial, explanation, created_at, updated_at) VALUES (@quiz_id, 4, 'single', 'La socialisation anticipatrice (R. K. Merton) désigne…', '{"choices":[{"id":"a","text":"l’intériorisation des normes d’un groupe auquel on souhaite appartenir","correct":true},{"id":"b","text":"la transmission des valeurs par les parents","correct":false},{"id":"c","text":"l’apprentissage des règles à l’école primaire","correct":false},{"id":"d","text":"la reproduction des comportements des grands-parents","correct":false}]}', 1.00, 30, 0, 'Merton montre que des individus adoptent par avance les valeurs du groupe de référence qu’ils veulent rejoindre.', UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO questions (quiz_id, position, type, prompt, data, points, time_limit, partial, explanation, created_at, updated_at) VALUES (@quiz_id, 5, 'truefalse', 'La socialisation s’arrête à la fin de l’adolescence.', '{"answer":false}', 1.00, 20, 0, 'La socialisation est un processus continu : la socialisation secondaire se poursuit tout au long de la vie.', UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
