<?php
defined('APP') || exit;

// Incidents that mean "the student left the quiz": they cancel the running question and may lock the attempt.
const EXIT_TYPES = ['hidden', 'blur', 'fullscreen', 'reload', 'device', 'ai_extension', 'devtools', 'gap', 'automation', 'split', 'hb_hidden', 'hb_blur', 'tamper'];
// Incidents the browser is allowed to report (others are generated by the server).
const CLIENT_INCIDENTS = ['hidden', 'blur', 'fullscreen', 'ai_extension', 'devtools', 'split', 'automation', 'paste', 'copy', 'shortcut', 'screenshot', 'print', 'multiscreen', 'typing', 'extension', 'back', 'mouse_out', 'tamper'];

const HEARTBEAT_GAP_MS = 10000;
const ANSWER_GRACE_MS = 2500;
const EXIT_MERGE_MS = 4000;
const MAX_INCIDENTS_PER_ATTEMPT = 1500;

const INCIDENT_LABELS = [
    'hidden' => 'A quitté la page / l’application',
    'blur' => 'A utilisé une autre fenêtre ou application',
    'fullscreen' => 'Est sorti du plein écran',
    'reload' => 'A rechargé la page pendant une question',
    'device' => 'S’est connecté depuis un autre appareil',
    'ai_extension' => 'Extension d’IA détectée dans le navigateur',
    'devtools' => 'Outils de développement ouverts',
    'gap' => 'Signal perdu (application quittée ou page figée)',
    'automation' => 'Navigateur automatisé détecté',
    'split' => 'Écran partagé / fenêtre réduite',
    'hb_hidden' => 'Page masquée (contrôle serveur)',
    'hb_blur' => 'Page sans le focus (contrôle serveur)',
    'paste' => 'Tentative de coller',
    'copy' => 'Tentative de copier',
    'shortcut' => 'Raccourci clavier bloqué',
    'screenshot' => 'Touche capture d’écran',
    'print' => 'Tentative d’impression',
    'multiscreen' => 'Plusieurs écrans détectés',
    'typing' => 'Texte inséré d’un coup (IA / dictée ?)',
    'extension' => 'Élément inconnu injecté dans la page',
    'back' => 'Tentative de retour arrière',
    'mouse_out' => 'Souris hors de la fenêtre',
    'warning_ack' => 'A lu l’avertissement',
    'tamper' => 'Modification du fonctionnement de la page',
    'teacher' => 'Action de la professeure',
];

function cast_attempt(array $a): array
{
    foreach (['id', 'quiz_id', 'user_id', 'attempt_no', 'current_index', 'points', 'exits', 'incidents', 'started_ms', 'last_seen_ms', 'away_ms'] as $k) {
        $a[$k] = (int) $a[$k];
    }
    foreach (['q_started_ms', 'deadline_ms', 'finished_ms', 'warning_ms'] as $k) {
        $a[$k] = $a[$k] !== null ? (int) $a[$k] : null;
    }
    $a['is_preview'] = (bool) $a['is_preview'];
    $a['zeroed'] = (bool) $a['zeroed'];
    $a['score'] = (float) $a['score'];
    $a['max_score'] = (float) $a['max_score'];
    return $a;
}

function attempt_for_update(int $id): array
{
    $a = row('SELECT * FROM attempts WHERE id = ? FOR UPDATE', [$id]);
    if (!$a) {
        fail('Copie introuvable.', 404, 'not_found');
    }
    return cast_attempt($a);
}

function own_attempt_for_update(int $id, array $user): array
{
    $a = attempt_for_update($id);
    if ($a['user_id'] !== (int) $user['id']) {
        fail('Copie introuvable.', 404, 'not_found');
    }
    return $a;
}

function save_attempt(array $a): void
{
    update('attempts', $a['id'], [
        'status' => $a['status'],
        'finish_reason' => $a['finish_reason'],
        'lock_reason' => $a['lock_reason'],
        'current_index' => $a['current_index'],
        'q_started_ms' => $a['q_started_ms'],
        'deadline_ms' => $a['deadline_ms'],
        'finished_ms' => $a['finished_ms'],
        'last_seen_ms' => $a['last_seen_ms'],
        'exits' => $a['exits'],
        'incidents' => $a['incidents'],
        'away_ms' => $a['away_ms'],
        'session_token' => $a['session_token'],
        'warning_text' => $a['warning_text'],
        'warning_ms' => $a['warning_ms'],
        'zeroed' => $a['zeroed'] ? 1 : 0,
    ]);
    recompute_attempt($a['id']);
}

function attempt_qids(array $a): array
{
    return array_map('intval', json_dec($a['question_ids']));
}

function current_question(array $a): ?array
{
    $qids = attempt_qids($a);
    $qid = $qids[$a['current_index']] ?? null;
    if ($qid === null) {
        return null;
    }
    return questions_by_ids([$qid])[$qid] ?? null;
}

function create_attempt(array $quiz, array $user, bool $preview): array
{
    $questions = quiz_questions($quiz['id']);
    if (!$questions) {
        fail('Ce quiz ne contient encore aucune question.');
    }
    $selected = $questions;
    if ($quiz['pool_size'] > 0 && $quiz['pool_size'] < count($questions)) {
        $pick = array_slice(secure_shuffle(array_keys($questions)), 0, $quiz['pool_size']);
        sort($pick);
        $selected = array_map(fn($i) => $questions[$i], $pick);
    }
    if ($quiz['shuffle_questions']) {
        $selected = secure_shuffle($selected);
    }
    $orders = [];
    foreach ($selected as $q) {
        if (in_array($q['type'], ['single', 'multiple'], true)) {
            $ids = array_column($q['data']['choices'], 'id');
            $orders[(string) $q['id']] = $quiz['shuffle_choices'] ? secure_shuffle($ids) : $ids;
        } elseif ($q['type'] === 'ordering') {
            $ids = array_column($q['data']['items'], 'id');
            $shuffled = secure_shuffle($ids);
            for ($i = 0; $i < 10 && $shuffled === $ids; $i++) {
                $shuffled = secure_shuffle($ids);
            }
            $orders[(string) $q['id']] = $shuffled;
        }
    }
    $now = now_ms();
    $attemptNo = 1 + (int) val('SELECT COUNT(*) FROM attempts WHERE quiz_id = ? AND user_id = ? AND is_preview = 0', [$quiz['id'], (int) $user['id']]);
    $id = insert('attempts', [
        'quiz_id' => $quiz['id'],
        'user_id' => (int) $user['id'],
        'attempt_no' => $preview ? 0 : min(255, $attemptNo),
        'is_preview' => $preview ? 1 : 0,
        'status' => 'in_progress',
        'question_ids' => json_enc(array_column($selected, 'id')),
        'choice_orders' => json_enc((object) $orders),
        'current_index' => 0,
        'q_started_ms' => null,
        'started_ms' => $now,
        'deadline_ms' => $quiz['time_limit'] > 0 ? $now + $quiz['time_limit'] * 1000 : null,
        'last_seen_ms' => $now,
        'max_score' => array_sum(array_column($selected, 'points')),
        'session_token' => (string) ($_SESSION['tok'] ?? ''),
        'ip' => client_ip(),
        'device' => device_label(user_agent(), str_in(input(), 'device_hint', 10)),
        'user_agent' => user_agent(),
    ]);
    return attempt_for_update($id);
}

function store_answer(array $a, array $q, ?array $response, string $status, array $grade, ?int $timeMs): void
{
    q(
        'INSERT IGNORE INTO answers (attempt_id, question_id, position, response, status, fraction, score, points, time_ms, created_ms) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)',
        [$a['id'], $q['id'], $a['current_index'], $response !== null ? json_enc($response) : null, $status, $grade['fraction'], $grade['score'], $grade['points'], $timeMs, now_ms()]
    );
}

function advance_attempt(array &$a): void
{
    $a['current_index']++;
    $a['q_started_ms'] = null;
    if ($a['current_index'] >= count(attempt_qids($a))) {
        finish_attempt($a, 'completed');
    }
}

function finish_attempt(array &$a, string $reason): void
{
    if ($a['status'] === 'finished') {
        return;
    }
    if ($a['q_started_ms'] !== null && ($q = current_question($a))) {
        store_answer($a, $q, null, 'timeout', ['fraction' => 0, 'score' => 0, 'points' => 0], now_ms() - $a['q_started_ms']);
    }
    $a['status'] = 'finished';
    $a['finish_reason'] = $reason;
    $a['lock_reason'] = null;
    $a['q_started_ms'] = null;
    $a['finished_ms'] = now_ms();
}

function cancel_current_question(array &$a): void
{
    if ($a['q_started_ms'] === null) {
        return;
    }
    $q = current_question($a);
    if ($q) {
        store_answer($a, $q, null, 'cancelled', ['fraction' => 0, 'score' => 0, 'points' => 0], now_ms() - $a['q_started_ms']);
    }
    advance_attempt($a);
}

function log_incident(array &$a, string $type, ?string $detail, ?int $durationMs, bool $counted, ?string $exitKey = null): void
{
    $a['incidents']++;
    if ($durationMs) {
        $a['away_ms'] += min($durationMs, 3600000);
    }
    if ($a['incidents'] > MAX_INCIDENTS_PER_ATTEMPT && !$counted) {
        return;
    }
    q(
        'INSERT IGNORE INTO incidents (attempt_id, type, detail, question_index, duration_ms, counted, exit_key, created_ms) VALUES (?, ?, ?, ?, ?, ?, ?, ?)',
        [$a['id'], $type, $detail !== null ? mb_substr($detail, 0, 255) : null, $a['status'] === 'finished' ? null : $a['current_index'], $durationMs !== null ? min($durationMs, 4000000000) : null, $counted ? 1 : 0, $exitKey, now_ms()]
    );
}

/**
 * The student left the quiz. The running question is cancelled (0 point) so that looking an answer up
 * elsewhere and coming back never pays; then the attempt is locked / submitted according to the quiz rules.
 */
function register_exit(array &$a, array $quiz, string $type, ?string $detail, ?int $durationMs, ?string $exitKey): array
{
    if ($exitKey !== null) {
        $existing = row('SELECT id, duration_ms FROM incidents WHERE attempt_id = ? AND exit_key = ?', [$a['id'], $exitKey]);
        if ($existing) {
            if ($durationMs && $durationMs > (int) $existing['duration_ms']) {
                $a['away_ms'] += $durationMs - (int) $existing['duration_ms'];
                q('UPDATE incidents SET duration_ms = ? WHERE id = ?', [$durationMs, (int) $existing['id']]);
            }
            return ['action' => null];
        }
    }
    $counted = $a['status'] === 'in_progress';
    // Several browser signals often describe the same absence (blur + hidden + heartbeat): count it once,
    // unless a new question was served since. Server-side detections are always distinct facts.
    if ($counted && !in_array($type, ['reload', 'device', 'gap'], true)) {
        $recent = val("SELECT MAX(created_ms) FROM incidents WHERE attempt_id = ? AND counted = 1 AND type NOT IN ('reload','device','gap')", [$a['id']]);
        if ($recent !== null && now_ms() - (int) $recent < EXIT_MERGE_MS && ($a['q_started_ms'] === null || $a['q_started_ms'] <= (int) $recent)) {
            $counted = false;
        }
    }
    log_incident($a, $type, $detail, $durationMs, $counted, $exitKey);
    if (!$counted) {
        return ['action' => null];
    }
    $a['exits']++;
    if ($quiz['exit_action'] === 'log') {
        return ['action' => 'warn', 'cancelled' => false];
    }
    $cancelled = $a['q_started_ms'] !== null;
    cancel_current_question($a);
    if ($a['status'] !== 'in_progress') {
        return ['action' => 'submit', 'cancelled' => $cancelled];
    }
    if ($a['exits'] > $quiz['max_exits']) {
        if ($quiz['exit_action'] === 'submit') {
            finish_attempt($a, 'exits');
            return ['action' => 'submit', 'cancelled' => $cancelled];
        }
        $a['status'] = 'locked';
        $a['lock_reason'] = INCIDENT_LABELS[$type] ?? 'Sortie du quiz détectée';
        return ['action' => 'lock', 'cancelled' => $cancelled];
    }
    return ['action' => 'warn', 'cancelled' => $cancelled];
}

/** Server-side clock: global deadline, silent client (heartbeat gap) and question time-outs. */
function sync_attempt(array &$a, array $quiz): void
{
    $now = now_ms();
    if ($a['status'] === 'finished') {
        return;
    }
    if ($a['deadline_ms'] !== null && $now > $a['deadline_ms'] + ANSWER_GRACE_MS) {
        finish_attempt($a, 'timeout');
        return;
    }
    if ($a['status'] !== 'in_progress' || $a['q_started_ms'] === null) {
        return;
    }
    $q = current_question($a);
    if (!$q) {
        finish_attempt($a, 'completed');
        return;
    }
    $qDeadline = $q['time_limit'] > 0 ? $a['q_started_ms'] + $q['time_limit'] * 1000 : null;
    $lastSeen = max($a['last_seen_ms'], $a['q_started_ms']);
    $gapEnd = $qDeadline !== null ? min($now, $qDeadline) : $now;
    if ($gapEnd - $lastSeen > HEARTBEAT_GAP_MS) {
        register_exit($a, $quiz, 'gap', 'Aucun signal pendant ' . round(($gapEnd - $lastSeen) / 1000) . ' s', $gapEnd - $lastSeen, 'gap-' . $a['current_index']);
    }
    if ($a['status'] === 'in_progress' && $a['q_started_ms'] !== null && $qDeadline !== null && $now > $qDeadline + ANSWER_GRACE_MS) {
        store_answer($a, $q, null, 'timeout', ['fraction' => 0, 'score' => 0, 'points' => 0], $q['time_limit'] * 1000);
        advance_attempt($a);
    }
}

/** Same account opened elsewhere during the attempt. */
function check_device(array &$a, array $quiz): void
{
    $tok = (string) ($_SESSION['tok'] ?? '');
    if ($tok !== '' && $a['session_token'] !== '' && !hash_equals($a['session_token'], $tok)) {
        if ($a['status'] !== 'finished') {
            register_exit($a, $quiz, 'device', device_label(user_agent()), null, null);
        }
        $a['session_token'] = $tok;
    }
}

function serve_question(array &$a): void
{
    if ($a['status'] === 'in_progress' && $a['q_started_ms'] === null && $a['current_index'] < count(attempt_qids($a))) {
        $a['q_started_ms'] = now_ms();
        $a['last_seen_ms'] = $a['q_started_ms'];
    }
}

function results_visible(array $quiz): bool
{
    return $quiz['feedback_mode'] !== 'release' || $quiz['results_released'];
}

function answer_streak(int $attemptId): int
{
    $streak = 0;
    foreach (rows('SELECT fraction FROM answers WHERE attempt_id = ? ORDER BY position DESC', [$attemptId]) as $r) {
        if ((float) $r['fraction'] < 1) {
            break;
        }
        $streak++;
    }
    return $streak;
}

function attempt_payload(array $a, array $quiz, array $user): array
{
    $qids = attempt_qids($a);
    $now = now_ms();
    $fresh = row('SELECT score, max_score, points FROM attempts WHERE id = ?', [$a['id']]);
    $p = [
        'attempt_id' => $a['id'],
        'status' => $a['status'],
        'finish_reason' => $a['finish_reason'],
        'lock_reason' => $a['lock_reason'],
        'index' => $a['current_index'],
        'total' => count($qids),
        'exits' => $a['exits'],
        'is_preview' => $a['is_preview'],
        'deadline_remaining_ms' => $a['deadline_ms'] !== null ? max(0, $a['deadline_ms'] - $now) : null,
        'warning' => $a['warning_text'] !== null ? ['id' => (int) $a['warning_ms'], 'text' => $a['warning_text']] : null,
        'student' => trim($user['first_name'] . ' ' . mb_strtoupper($user['last_name'])),
        'quiz' => [
            'id' => $quiz['id'],
            'title' => $quiz['title'],
            'level' => $quiz['level'],
            'feedback_mode' => $quiz['feedback_mode'],
            'require_fullscreen' => $quiz['require_fullscreen'],
            'max_exits' => $quiz['max_exits'],
            'exit_action' => $quiz['exit_action'],
            'time_limit' => $quiz['time_limit'],
            'show_leaderboard' => $quiz['show_leaderboard'],
        ],
        'points' => $quiz['feedback_mode'] === 'immediate' ? (int) $fresh['points'] : null,
        'question' => null,
        'result' => null,
    ];
    if ($a['status'] === 'in_progress' && $a['q_started_ms'] !== null && ($q = current_question($a))) {
        $pub = public_question($q, json_dec($a['choice_orders']));
        $pub['remaining_ms'] = $q['time_limit'] > 0 ? max(0, $a['q_started_ms'] + $q['time_limit'] * 1000 - $now) : null;
        $p['question'] = $pub;
    }
    if ($a['status'] === 'finished' && ($a['is_preview'] || results_visible($quiz))) {
        $p['result'] = [
            'score' => (float) $fresh['score'],
            'max_score' => (float) $fresh['max_score'],
            'note20' => note20((float) $fresh['score'], (float) $fresh['max_score']),
            'points' => (int) $fresh['points'],
            'zeroed' => $a['zeroed'],
        ];
    }
    return $p;
}

/** Full correction of a finished attempt (used for students and the teacher). */
function attempt_corrections(array $a, bool $withTiming = true): array
{
    $qids = attempt_qids($a);
    $questions = questions_by_ids($qids);
    $answers = [];
    foreach (rows('SELECT * FROM answers WHERE attempt_id = ?', [$a['id']]) as $ans) {
        $answers[(int) $ans['question_id']] = $ans;
    }
    $orders = json_dec($a['choice_orders']);
    $out = [];
    foreach ($qids as $pos => $qid) {
        $q = $questions[$qid] ?? null;
        if (!$q) {
            continue;
        }
        $ans = $answers[$qid] ?? null;
        $item = [
            'position' => $pos,
            'question' => public_question($q, $orders),
            'correction' => correction_of($q),
            'explanation' => $q['explanation'],
            'answer_id' => $ans ? (int) $ans['id'] : null,
            'response' => $ans ? json_dec($ans['response'], null) : null,
            'status' => $ans ? $ans['status'] : 'unanswered',
            'fraction' => $ans ? (float) $ans['fraction'] : 0.0,
            'score' => $ans ? (float) ($ans['override_score'] ?? $ans['score']) : 0.0,
            'auto_score' => $ans ? (float) $ans['score'] : 0.0,
            'overridden' => $ans && $ans['override_score'] !== null,
            'max' => $q['points'],
        ];
        if ($withTiming) {
            $item['time_ms'] = $ans && $ans['time_ms'] !== null ? (int) $ans['time_ms'] : null;
            $item['points'] = $ans ? (int) $ans['points'] : 0;
        }
        $out[] = $item;
    }
    return $out;
}

function ip_allowed(array $quiz): bool
{
    $list = trim((string) ($quiz['allowed_ips'] ?? ''));
    if ($list === '') {
        return true;
    }
    $ip = client_ip();
    foreach (preg_split('/[\s,;]+/', $list) as $rule) {
        if ($rule === '') {
            continue;
        }
        if (str_ends_with($rule, '*') && str_starts_with($ip, rtrim($rule, '*'))) {
            return true;
        }
        if ($rule === $ip) {
            return true;
        }
    }
    return false;
}
